In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
url = 'https://raw.githubusercontent.com/nicknochnack/Tensorflow-in-10-Minutes/main/Churn.csv'
df = pd.read_csv(url)
df.head()

,Customer ID,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,7590-VHVEA,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [5]:
#Preprocessing stage by using one hot encoding to convert data to numerical to be used in modeling
#Assigning the x and y variable
x = pd.get_dummies(df.drop(['Churn', 'Customer ID'], axis=1))
y = df['Churn'].apply(lambda x:1 if x =='Yes' else 0)

In [6]:
#Splitting training and test dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

In [7]:
x_train.head()

,Senior Citizen,tenure,Monthly Charges,Gender_Female,Gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,Phone Service_No,...,Total Charges_995.35,Total Charges_996.45,Total Charges_996.85,Total Charges_996.95,Total Charges_997.65,Total Charges_997.75,Total Charges_998.1,Total Charges_999.45,Total Charges_999.8,Total Charges_999.9
261,1,3,41.15,0,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
5172,0,12,45.90,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3338,0,7,75.35,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4010,0,63,86.70,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3899,0,48,25.05,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
y_train.head()

261     1
5172    0
3338    0
4010    0
3899    0
Name: Churn, dtype: int64

In [10]:
pip install tensorflow

Collecting tensorflow
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e4/14/d795bb156f8cc10eb1dcfe1332b7dbb8405b634688980aa9be8f885cc888/tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Downloading tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Collecting tensorflow-intel==2.16.1 (from tensorflow)
  Obtaining dependency information for tensorflow-intel==2.16.1 from https://files.pythonhosted.org/packages/e0/36/6278e4e7e69a90c00e0f82944d8f2713dd85a69d1add455d9e50446837ab/tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Downloading tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/41/f0/7e988a019bc54b2dbd0ad4182ef2d53488bb02e58694cd79d61369e85900/flatbuffers-24.3.25-py2.py3-none-any.whl.metadata
  Downloading flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 from https://files.pythonhosted.org/packages/fa/39/5aae571e5a5f4de9c3445dae08a530498e5c53b0e74410eeeb0991c79047/gast-0.5.4-py3-none-any.whl.metadata
  Downloading gast-0.5.4-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for google-pasta>=0.1.1 from https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl.metadata
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py>=3.10.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for h5py>=3.10.0 from https://files.pythonhosted.org/packages/d8/5e/b7b83cfe60504cc4d24746aed04353af7ea8ec104e597e5ae71b8d0390cb/h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata
  Downloading h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for libclang>=13.0.0 from https://files.pythonhosted.org/packages/0b/2d/3f480b1e1d31eb3d6de5e3ef641954e5c67430d5ac93b7fa7e07589576c7/libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting ml-dtypes~=0.3.1 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for ml-dtypes~=0.3.1 from https://files.pythonhosted.org/packages/a4/db/1784b87285588788170f87e987bfb4bda218d62a70a81ebb66c94e7f9b95/ml_dtypes-0.3.2-cp311-cp311-win_amd64.whl.metadata
  Downloading ml_dtypes-0.3.2-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for opt-einsum>=2.3.2 from https://files.pythonhosted.org/packages/bc/19/404708a7e54ad2798907210462fd950c3442ea51acc8790f3da48d2bee8b/opt_einsum-3.3.0-py3-none-any.whl.metadata
  Downloading opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: packaging in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (23.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 from https://files.pythonhosted.org/packages/ad/6e/1bed3b7c904cc178cb8ee8dbaf72934964452b3de95b7a63412591edb93c/protobuf-4.25.3-cp310-abi3-win_amd64.whl.metadata
  Downloading protobuf-4.25.3-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.31.0)
Requirement already satisfied: setuptools in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for termcolor>=1.1.0 from https://files.pythonhosted.org/packages/d9/5f/8c716e47b3a50cbd7c146f45881e11d9414def768b7cd9c5e6650ec2a80a/termcolor-2.4.0-py3-none-any.whl.metadata
  Downloading termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (4.7.1)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/bc/4f/22cdc1d2073593aac4c0cfee7d69418c6dad24069372e3f6e6706673daa6/grpcio-1.64.0-cp311-cp311-win_amd64.whl.metadata
  Downloading grpcio-1.64.0-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Collecting tensorboard<2.17,>=2.16 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for tensorboard<2.17,>=2.16 from https://files.pythonhosted.org/packages/3a/d0/b97889ffa769e2d1fdebb632084d5e8b53fc299d43a537acee7ec0c021a3/tensorboard-2.16.2-py3-none-any.whl.metadata
  Downloading tensorboard-2.16.2-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.0.0 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for keras>=3.0.0 from https://files.pythonhosted.org/packages/8d/44/c604ecc5c9993b6574a681f2f505e980725871a89cfd9e48597b12ccb506/keras-3.3.3-py3-none-any.whl.metadata
  Downloading keras-3.3.3-py3-none-any.whl.metadata (5.7 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for tensorflow-io-gcs-filesystem>=0.23.1 from https://files.pythonhosted.org/packages/ac/4e/9566a313927be582ca99455a9523a097c7888fc819695bdc08415432b202/tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl.metadata
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.24.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\lim otto\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.16.1->tensorflow) (0.38.4)
Collecting rich (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/87/67/a37f6214d0e9fe57f6ae54b2956d550ca8365857f42a1ce0392bb21d9410/rich-13.7.1-py3-none-any.whl.metadata
  Downloading rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for namex from https://files.pythonhosted.org/packages/73/59/7854fbfb59f8ae35483ce93493708be5942ebb6328cd85b3a609df629736/namex-0.0.8-py3-none-any.whl.metadata
  Downloading namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
Collecting optree (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for optree from https://files.pythonhosted.org/packages/8f/db/e05a35451d4ba30fdc65ef168dfdc68a6939ea6afdc0101e3e77f97e1547/optree-0.11.0-cp311-cp311-win_amd64.whl.metadata
  Downloading optree-0.11.0-cp311-cp311-win_amd64.whl.metadata (46 kB)
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lim otto\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lim otto\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lim otto\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lim otto\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2023.7.22)
Requirement already satisfied: markdown>=2.6.8 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (3.4.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow)
  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/7a/13/e503968fefabd4c6b2650af21e110aa8466fe21432cd7c43a84577a89438/tensorboard_data_server-0.7.2-py3-none-any.whl.metadata
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\lim otto\anaconda3\lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (2.2.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\lim otto\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (2.1.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lim otto\anaconda3\lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lim otto\anaconda3\lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\lim otto\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.1.0)
Downloading tensorflow-2.16.1-cp311-cp311-win_amd64.whl (2.1 kB)
Downloading tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl (377.0 MB)
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/377.0 MB 5.1 MB/s eta 0:01:14
   ---------------------------------------- 0.1/377.0 MB 1.2 MB/s eta 0:05:19
   ---------------------------------------- 0.3/377.0 MB 1.7 MB/s eta 0:03:37
   ---------------------------------------- 0.4/377.0 MB 2.3 MB/s eta 0:02:47
   ---------------------------------------- 0.6/377.0 MB 2.6 MB/s eta 0:02:24
   ---------------------------------------- 0.7/377.0 MB 2.3 MB/s eta 0:02:42
   ---------------------------------------- 0.9/377.0 MB 2.7 MB/s eta 0:02:21
   ---------------------------------------- 1.0/377.0 MB 2.7 MB/s eta 0:02:21
   ---------------------------------------- 1.2/377.0 MB 2.9 MB/s eta 0:02:10
   ---------------------------------------- 1.6/377.0 MB 3.4 MB/s eta 0:01:50
   ---------------------------------------- 1.8/377.0 MB 3.6 MB/s eta 0:01:44
   ---------------------------------------- 2.3/377.0 MB 4.1 MB/s eta 0:01:32
   ---------------------------------------- 2.7/377.0 MB 4.5 MB/s eta 0:01:24
   ---------------------------------------- 3.2/377.0 MB 5.0 MB/s eta 0:01:15
   ---------------------------------------- 3.7/377.0 MB 5.3 MB/s eta 0:01:10
   ---------------------------------------- 4.1/377.0 MB 5.7 MB/s eta 0:01:05
   ---------------------------------------- 4.2/377.0 MB 5.3 MB/s eta 0:01:10
   ---------------------------------------- 4.2/377.0 MB 5.3 MB/s eta 0:01:11
   ---------------------------------------- 4.4/377.0 MB 5.2 MB/s eta 0:01:12
   ---------------------------------------- 4.4/377.0 MB 5.2 MB/s eta 0:01:12
   ---------------------------------------- 4.5/377.0 MB 4.7 MB/s eta 0:01:20
   ---------------------------------------- 4.6/377.0 MB 4.7 MB/s eta 0:01:19
   ---------------------------------------- 4.7/377.0 MB 4.5 MB/s eta 0:01:23
   ---------------------------------------- 4.7/377.0 MB 4.5 MB/s eta 0:01:23
    --------------------------------------- 4.8/377.0 MB 4.1 MB/s eta 0:01:31
    --------------------------------------- 4.9/377.0 MB 4.2 MB/s eta 0:01:30
    --------------------------------------- 5.1/377.0 MB 4.2 MB/s eta 0:01:30
    --------------------------------------- 5.2/377.0 MB 4.0 MB/s eta 0:01:33
    --------------------------------------- 5.2/377.0 MB 3.9 MB/s eta 0:01:37
    --------------------------------------- 5.2/377.0 MB 3.9 MB/s eta 0:01:37
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.3/377.0 MB 3.7 MB/s eta 0:01:40
    --------------------------------------- 5.9/377.0 MB 3.0 MB/s eta 0:02:05
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.0/377.0 MB 3.0 MB/s eta 0:02:02
    --------------------------------------- 6.1/377.0 MB 2.7 MB/s eta 0:02:18
    --------------------------------------- 6.2/377.0 MB 2.7 MB/s eta 0:02:18
    --------------------------------------- 6.3/377.0 MB 2.6 MB/s eta 0:02:21
    --------------------------------------- 6.3/377.0 MB 2.6 MB/s eta 0:02:24
    --------------------------------------- 6.4/377.0 MB 2.6 MB/s eta 0:02:23
    --------------------------------------- 6.5/377.0 MB 2.6 MB/s eta 0:02:23
    --------------------------------------- 6.6/377.0 MB 2.6 MB/s eta 0:02:26
    --------------------------------------- 6.7/377.0 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 6.7/377.0 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 6.8/377.0 MB 2.5 MB/s eta 0:02:28
    --------------------------------------- 6.9/377.0 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 7.1/377.0 MB 2.5 MB/s eta 0:02:28
    --------------------------------------- 7.1/377.0 MB 2.5 MB/s eta 0:02:28
    --------------------------------------- 7.2/377.0 MB 2.5 MB/s eta 0:02:29
    --------------------------------------- 7.3/377.0 MB 2.5 MB/s eta 0:02:29
    --------------------------------------- 7.4/377.0 MB 2.5 MB/s eta 0:02:31
    --------------------------------------- 7.4/377.0 MB 2.5 MB/s eta 0:02:31
    --------------------------------------- 7.5/377.0 MB 2.5 MB/s eta 0:02:31
    --------------------------------------- 7.7/377.0 MB 2.4 MB/s eta 0:02:32
    --------------------------------------- 7.7/377.0 MB 2.4 MB/s eta 0:02:33
    --------------------------------------- 7.8/377.0 MB 2.4 MB/s eta 0:02:31
    --------------------------------------- 7.8/377.0 MB 2.4 MB/s eta 0:02:31
    --------------------------------------- 8.0/377.0 MB 2.4 MB/s eta 0:02:34
    --------------------------------------- 8.0/377.0 MB 2.4 MB/s eta 0:02:37
    --------------------------------------- 8.2/377.0 MB 2.4 MB/s eta 0:02:34
    --------------------------------------- 8.3/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 8.4/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 8.5/377.0 MB 2.4 MB/s eta 0:02:36
    --------------------------------------- 8.6/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 8.7/377.0 MB 2.4 MB/s eta 0:02:34
    --------------------------------------- 8.8/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 8.9/377.0 MB 2.4 MB/s eta 0:02:36
    --------------------------------------- 9.0/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 9.1/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 9.1/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 9.1/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 9.1/377.0 MB 2.4 MB/s eta 0:02:35
    --------------------------------------- 9.1/377.0 MB 2.3 MB/s eta 0:02:42
    --------------------------------------- 9.3/377.0 MB 2.3 MB/s eta 0:02:42
    --------------------------------------- 9.3/377.0 MB 2.3 MB/s eta 0:02:42
    --------------------------------------- 9.3/377.0 MB 2.3 MB/s eta 0:02:42
   - -------------------------------------- 9.6/377.0 MB 2.3 MB/s eta 0:02:43
   - -------------------------------------- 9.6/377.0 MB 2.2 MB/s eta 0:02:44
   - -------------------------------------- 9.7/377.0 MB 2.2 MB/s eta 0:02:44
   - -------------------------------------- 9.8/377.0 MB 2.2 MB/s eta 0:02:44
   - -------------------------------------- 9.9/377.0 MB 2.3 MB/s eta 0:02:44
   - -------------------------------------- 10.0/377.0 MB 2.3 MB/s eta 0:02:43
   - -------------------------------------- 10.1/377.0 MB 2.2 MB/s eta 0:02:45
   - -------------------------------------- 10.2/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.2/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.2/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.4/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.5/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.5/377.0 MB 2.2 MB/s eta 0:02:46
   - -------------------------------------- 10.5/377.0 MB 2.2 MB/s eta 0:02:48
   - -------------------------------------- 10.7/377.0 MB 2.2 MB/s eta 0:02:49
   - -------------------------------------- 10.8/377.0 MB 2.2 MB/s eta 0:02:50
   - -------------------------------------- 10.8/377.0 MB 2.2 MB/s eta 0:02:50
   - -------------------------------------- 10.8/377.0 MB 2.2 MB/s eta 0:02:51
   - -------------------------------------- 10.9/377.0 MB 2.1 MB/s eta 0:02:52
   - -------------------------------------- 10.9/377.0 MB 2.1 MB/s eta 0:02:54
   - -------------------------------------- 11.1/377.0 MB 2.1 MB/s eta 0:02:54
   - -------------------------------------- 11.1/377.0 MB 2.1 MB/s eta 0:02:55
   - -------------------------------------- 11.2/377.0 MB 2.1 MB/s eta 0:02:57
   - -------------------------------------- 11.2/377.0 MB 2.1 MB/s eta 0:02:57
   - -------------------------------------- 11.3/377.0 MB 2.1 MB/s eta 0:02:59

In [11]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [13]:
#Creating Sequential model, with linear stack of layers that can be used to build neural networks in a straightforward and simple manner
model = Sequential()
#Adding hidden layers
#In the parameters, input will be the same amt of dimension available in x_train column
model.add(Dense(units=32, activation='relu', input_dim=len(x_train.columns)))
model.add(Dense(units=64, activation='relu'))
#Output layer with 1, to predict yes or no result
model.add(Dense(units=1, activation='sigmoid'))

C:\Users\Lim Otto\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
#Compiling model by ordering the model to use specific optimizer, metrics in the parameters
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [16]:
#Training the model with training sets split earlier
model.fit(x_train, y_train, epochs=200, batch_size=32)

Epoch 1/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7404 - loss: 0.5302
Epoch 2/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7670 - loss: 0.4931
Epoch 3/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.4880
Epoch 4/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7638 - loss: 0.4911
Epoch 5/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4867
Epoch 6/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7748 - loss: 0.4796
Epoch 7/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7712 - loss: 0.4825
Epoch 8/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7771 - loss: 0.4749
Epoch 9/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7738 - loss: 0.4778
Epoch 10/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7725 - loss: 0.4715
Epoch 11/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7791 - loss: 0.4698
Epoch 12/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7827 - loss: 0.4603
Epoch 13/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7827 - loss: 0.4564
Epoch 14/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7757 - loss: 0.4712
Epoch 15/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7797 - loss: 0.4586
Epoch 16/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7889 - loss: 0.4556
Epoch 17/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7689 - loss: 0.4775
Epoch 18/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7894 - loss: 0.4498
Epoch 19/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7806 - loss: 0.4662
Epoch 20/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7679 - loss: 0.4714
Epoch 21/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7730 - loss: 0.4633
Epoch 22/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7751 - loss: 0.4627
Epoch 23/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7852 - loss: 0.4506
Epoch 24/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7820 - loss: 0.4545
Epoch 25/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7819 - loss: 0.4680
Epoch 26/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7765 - loss: 0.4594
Epoch 27/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7738 - loss: 0.4695
Epoch 28/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7875 - loss: 0.4508
Epoch 29/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7863 - loss: 0.4579
Epoch 30/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7885 - loss: 0.4475
Epoch 31/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7742 - loss: 0.4616
Epoch 32/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7807 - loss: 0.4662
Epoch 33/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7884 - loss: 0.4495
Epoch 34/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7884 - loss: 0.4369
Epoch 35/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7863 - loss: 0.4510
Epoch 36/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7873 - loss: 0.4526
Epoch 37/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7716 - loss: 0.4635
Epoch 38/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7803 - loss: 0.4584
Epoch 39/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7820 - loss: 0.4607
Epoch 40/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7872 - loss: 0.4572
Epoch 41/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7810 - loss: 0.4544
Epoch 42/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7878 - loss: 0.4481
Epoch 43/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7796 - loss: 0.4561
Epoch 44/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7869 - loss: 0.4457
Epoch 45/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7767 - loss: 0.4686
Epoch 46/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7823 - loss: 0.4587
Epoch 47/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7889 - loss: 0.4540
Epoch 48/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7889 - loss: 0.4418
Epoch 49/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7872 - loss: 0.4490
Epoch 50/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7856 - loss: 0.4461
Epoch 51/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7806 - loss: 0.4542
Epoch 52/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7862 - loss: 0.4511
Epoch 53/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7941 - loss: 0.4475
Epoch 54/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7829 - loss: 0.4479
Epoch 55/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7874 - loss: 0.4352
Epoch 56/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7806 - loss: 0.4547
Epoch 57/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7887 - loss: 0.4436
Epoch 58/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7775 - loss: 0.4623
Epoch 59/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7823 - loss: 0.4489
Epoch 60/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7878 - loss: 0.4396
Epoch 61/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7796 - loss: 0.4518
Epoch 62/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7850 - loss: 0.4483
Epoch 63/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7909 - loss: 0.4467
Epoch 64/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7851 - loss: 0.4511
Epoch 65/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7825 - loss: 0.4551
Epoch 66/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7810 - loss: 0.4530
Epoch 67/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7866 - loss: 0.4403
Epoch 68/200

177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7724 - loss: 0.4975
Epoch 69/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7783 - loss: 0.4539
Epoch 70/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7851 - loss: 0.4501
Epoch 71/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7851 - loss: 0.4506
Epoch 72/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7797 - loss: 0.4467
Epoch 73/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7812 - loss: 0.4487
Epoch 74/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7839 - loss: 0.4484
Epoch 75/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7809 - loss: 0.4590
Epoch 76/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7725 - loss: 0.4564
Epoch 77/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7884 - loss: 0.4388
Epoch 78/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7807 - loss: 0.4481
Epoch 79/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7955 - loss: 0.4324
Epoch 80/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7997 - loss: 0.4287
Epoch 81/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4639
Epoch 82/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7959 - loss: 0.4477
Epoch 83/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7853 - loss: 0.4502
Epoch 84/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7823 - loss: 0.4443
Epoch 85/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4332
Epoch 86/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7876 - loss: 0.4473
Epoch 87/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7885 - loss: 0.4439
Epoch 88/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7758 - loss: 0.4420
Epoch 89/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7886 - loss: 0.4398
Epoch 90/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7906 - loss: 0.4388
Epoch 91/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7765 - loss: 0.4542
Epoch 92/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7899 - loss: 0.4398
Epoch 93/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7837 - loss: 0.4432
Epoch 94/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7860 - loss: 0.4483
Epoch 95/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7969 - loss: 0.4390
Epoch 96/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7901 - loss: 0.4453
Epoch 97/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7942 - loss: 0.4352
Epoch 98/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7672 - loss: 0.4731
Epoch 99/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7824 - loss: 0.4557
Epoch 100/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7869 - loss: 0.4448
Epoch 101/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7882 - loss: 0.4445
Epoch 102/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7936 - loss: 0.4395
Epoch 103/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7782 - loss: 0.4560
Epoch 104/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7912 - loss: 0.4313
Epoch 105/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7964 - loss: 0.4269
Epoch 106/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7825 - loss: 0.4487
Epoch 107/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7971 - loss: 0.4271
Epoch 108/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7966 - loss: 0.4336
Epoch 109/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7861 - loss: 0.4414
Epoch 110/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7888 - loss: 0.4340
Epoch 111/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7910 - loss: 0.4343
Epoch 112/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8038 - loss: 0.4089
Epoch 113/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7861 - loss: 0.4428
Epoch 114/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7940 - loss: 0.4327
Epoch 115/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7957 - loss: 0.4336
Epoch 116/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4427
Epoch 117/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7932 - loss: 0.4301
Epoch 118/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7906 - loss: 0.4408
Epoch 119/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7874 - loss: 0.4471
Epoch 120/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8022 - loss: 0.4254
Epoch 121/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7863 - loss: 0.4338
Epoch 122/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7879 - loss: 0.4364
Epoch 123/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7947 - loss: 0.4386
Epoch 124/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7839 - loss: 0.4395
Epoch 125/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7774 - loss: 0.4514
Epoch 126/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7900 - loss: 0.4351
Epoch 127/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7964 - loss: 0.4306
Epoch 128/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7852 - loss: 0.4387
Epoch 129/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4301
Epoch 130/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7907 - loss: 0.4401
Epoch 131/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7827 - loss: 0.4487
Epoch 132/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7756 - loss: 0.4691
Epoch 133/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7886 - loss: 0.4523
Epoch 134/200

177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7901 - loss: 0.4444
Epoch 135/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4390
Epoch 136/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8021 - loss: 0.4296
Epoch 137/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7954 - loss: 0.4352
Epoch 138/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7836 - loss: 0.4409
Epoch 139/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7915 - loss: 0.4322
Epoch 140/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8062 - loss: 0.4225
Epoch 141/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7824 - loss: 0.4556
Epoch 142/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7856 - loss: 0.4400
Epoch 143/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7944 - loss: 0.4267
Epoch 144/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8027 - loss: 0.4263
Epoch 145/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7866 - loss: 0.4329
Epoch 146/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7880 - loss: 0.4433
Epoch 147/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7888 - loss: 0.4376
Epoch 148/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7909 - loss: 0.4338
Epoch 149/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7906 - loss: 0.4366
Epoch 150/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7916 - loss: 0.4296
Epoch 151/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4240
Epoch 152/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7968 - loss: 0.4337
Epoch 153/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7946 - loss: 0.4377
Epoch 154/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4291
Epoch 155/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7974 - loss: 0.4295
Epoch 156/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4339
Epoch 157/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7974 - loss: 0.4214
Epoch 158/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7933 - loss: 0.4378
Epoch 159/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8004 - loss: 0.4240
Epoch 160/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7961 - loss: 0.4290
Epoch 161/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7782 - loss: 0.4433
Epoch 162/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7880 - loss: 0.4308
Epoch 163/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7855 - loss: 0.4422
Epoch 164/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7911 - loss: 0.4344
Epoch 165/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7952 - loss: 0.4213
Epoch 166/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7930 - loss: 0.4246
Epoch 167/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7974 - loss: 0.4198
Epoch 168/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7964 - loss: 0.4285
Epoch 169/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7936 - loss: 0.4360
Epoch 170/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7880 - loss: 0.4413
Epoch 171/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7823 - loss: 0.4532
Epoch 172/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.4270
Epoch 173/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7827 - loss: 0.4481
Epoch 174/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7979 - loss: 0.4293
Epoch 175/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7960 - loss: 0.4329
Epoch 176/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7958 - loss: 0.4323
Epoch 177/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8082 - loss: 0.4110
Epoch 178/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7901 - loss: 0.4412
Epoch 179/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7804 - loss: 0.4538
Epoch 180/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7949 - loss: 0.4356
Epoch 181/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8004 - loss: 0.4250
Epoch 182/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7745 - loss: 0.4596
Epoch 183/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7927 - loss: 0.4353
Epoch 184/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7952 - loss: 0.4479
Epoch 185/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7951 - loss: 0.4258
Epoch 186/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7887 - loss: 0.4495
Epoch 187/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7944 - loss: 0.4357
Epoch 188/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7972 - loss: 0.4283
Epoch 189/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7923 - loss: 0.4328
Epoch 190/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8014 - loss: 0.4268
Epoch 191/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8040 - loss: 0.4265
Epoch 192/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7878 - loss: 0.4409
Epoch 193/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7984 - loss: 0.4254
Epoch 194/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7977 - loss: 0.4306
Epoch 195/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7937 - loss: 0.4314
Epoch 196/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7979 - loss: 0.4272
Epoch 197/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7920 - loss: 0.4321
Epoch 198/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.4343
Epoch 199/200
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8065 - loss: 0.4257
Epoch 200/200

177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7973 - loss: 0.4227

In [17]:
#Using the model for Predictions on the test sets
y_pred = model.predict(x_test)

#Convert result into binary outcome by using list comprehension
y_pred = [0 if val <0.5 else 1 for val in y_pred]

45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [19]:
#Evaluate results using accuracy score from sklearn
accuracy_score(y_test, y_pred)

0.8126330731014905